### ISSUE TITLE
publish as a module in npmjs.org

### ISSUE THREAD

**Issue by ianhuynh** [kineticadb/kinetica-api-javascript#1]
any chance you guys would consider publishing this as an NPM module?

**Comment by gpudb-nnegahban** [comment]
yes definitely, also doing the same for python and pypi. 

I'll reply on here when I have more knowledge on timing.

**Comment by kylesutton** [comment]
The latest release is 7.1.8-2, available here:  https://www.npmjs.com/package/@kinetica/gpudb/v/7.1.8-2
